apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: secure-monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
      - job_name: 'ci-api'                 # Nom du job adapté
        metrics_path: /metrics             # Chemin d’accès aux métriques exposées par ton app
        static_configs:
          - targets: ['ci-api-service.secure-app.svc.cluster.local:80']  # Nom complet DNS du service + port
