name: CI/CD - Secure K8s App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    env:
      IMAGE_NAME: ${{ secrets.DOCKER_USER }}/secure-ci-k8s-api:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME ./app

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Set kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > kconfig
          chmod 600 kconfig

      - name: Apply namespace for app
        run: kubectl --kubeconfig=kconfig apply -f infra-k8s/secure-app/namespace.yaml

      - name: Apply K8s manifests for app
        run: |
          kubectl --kubeconfig=kconfig apply -f infra-k8s/secure-app/
          kubectl --kubeconfig=kconfig rollout status deployment/ci-api -n secure-app

      - name: Apply namespace for monitoring
        run: kubectl --kubeconfig=kconfig apply -f infra-k8s/secure-monitoring/namespace.yaml

      - name: Wait for monitoring namespace
        run: |
          for i in {1..5}; do
            kubectl --kubeconfig=kconfig get ns secure-monitoring && break || sleep 2
          done

      - name: Apply K8s manifests for monitoring
        run: |
          kubectl --kubeconfig=kconfig apply -f infra-k8s/secure-monitoring/
          kubectl --kubeconfig=kconfig rollout status deployment/grafana -n secure-monitoring
          kubectl --kubeconfig=kconfig rollout status deployment/prometheus -n secure-monitoring
