name: CI/CD - Secure K8s App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    env:
      IMAGE_NAME: ${{ secrets.DOCKER_USER }}/secure-k8s-app:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build & push image
        run: |
          docker build -t $IMAGE_NAME ./app
          docker push $IMAGE_NAME

      - name: Set kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > kconfig
          chmod 600 kconfig

      - name: Apply K8s manifests for app
        run: |
          kubectl --kubeconfig=kconfig apply -f infra-k8s/app/namespace.yaml
          kubectl --kubeconfig=kconfig apply -f infra-k8s/app/
          kubectl --kubeconfig=kconfig rollout status deployment/secure-app -n secure-app

      - name: Apply K8s manifests for monitoring
        run: |
          kubectl --kubeconfig=kconfig apply -f infra-k8s/monitoring/
          kubectl --kubeconfig=kconfig rollout status deployment/grafana -n secure-monitoring
          kubectl --kubeconfig=kconfig rollout status deployment/prometheus -n secure-monitoring
